/* sttest -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "sttest.h"

const char *Sttest_name = "Sttest";

/* O2SM INTERFACE: /arco/sttest/new int32 id, int32 input, float hz1, float hz2;
 */
void arco_sttest_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t input = argv[1]->i;
    float hz1 = argv[2]->f;
    float hz2 = argv[3]->f;
    // end unpack message

    ANY_UGEN_FROM_ID(input_ugen, input, "arco_sttest_new");

    new Sttest(id, input_ugen, hz1, hz2);
}


/* O2SM INTERFACE: /arco/sttest/repl_input int32 id, int32 input_id;
 */
static void arco_sttest_repl_input(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t input_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Sttest, sttest, id, "arco_sttest_repl_input");
    ANY_UGEN_FROM_ID(input, input_id, "arco_sttest_repl_input");
    sttest->repl_input(input);
}


/* O2SM INTERFACE: /arco/sttest/set_input int32 id, int32 chan, float val;
 */
static void arco_sttest_set_input (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Sttest, sttest, id, "arco_sttest_set_input");
    sttest->set_input(chan, val);
}


static void sttest_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/sttest/new", "iiff", arco_sttest_new, NULL, true,
                    true);
    o2sm_method_new("/arco/sttest/repl_input", "ii", arco_sttest_repl_input,
                    NULL, true, true);
    o2sm_method_new("/arco/sttest/set_input", "iif", arco_sttest_set_input,
                    NULL, true, true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer sttest_init_obj(sttest_init);
