/* sttest -- unit generator for arco
 *
 * generated by f2a.py
 */

/*------------- BEGIN FAUST PREAMBLE -------------*/

/* ------------------------------------------------------------
name: "sttest"
Code generated with Faust 2.75.7 (https://faust.grame.fr)
Compilation options: -lang cpp -light -ct 1 -cn Sttest -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */

#ifndef  __Sttest_H__
#define  __Sttest_H__

#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif 

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#ifndef FAUSTCLASS 
#define FAUSTCLASS Sttest
#endif

#ifdef __APPLE__ 
#define exp10f __exp10f
#define exp10 __exp10
#endif

#if defined(_WIN32)
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif
/*-------------- END FAUST PREAMBLE --------------*/

extern const char *Sttest_name;

class Sttest : public Ugen {
public:
    struct Sttest_state {
        FAUSTFLOAT fEntry0;
        float fVec0[2];
        float fRec0[2];
        FAUSTFLOAT fEntry1;
        float fVec1[2];
        float fRec1[2];
    };
    Vec<Sttest_state> states;
    void (Sttest::*run_channel)(Sttest_state *state);

    Ugen_ptr input;
    int input_stride;
    Sample_ptr input_samps;

    float hz1;
    float hz2;
    float fConst0;

    Sttest(int id, Ugen_ptr input_, float hz1_, float hz2_) :
            Ugen(id, 'a', 2) {
        input = input_;
        hz1 = hz1_;
        hz2 = hz2_;
        flags = CAN_TERMINATE;
        states.set_size(chans);
        fConst0 = 3.1415927f / std::min<float>(1.92e+05f, std::max<float>(1.0f, float(AR)));
        init_input(input);
        run_channel = (void (Sttest::*)(Sttest_state *)) 0;
        update_run_channel();
    }

    ~Sttest() {
        input->unref(&input);
    }

    const char *classname() { return Sttest_name; }

#if ARCO_REF_DEBUG
    // for tracing tree of Ugens
    bool get_ref(int i, Ugen **child) {
        if (i == 0) { *child = input;
        } else { return false;
        }
        return true;
    }
#endif

    void initialize_channel_states() {
        for (int i = 0; i < chans; i++) {
            for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
                states[i].fVec0[l0] = 0.0f;
            }
            for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
                states[i].fRec0[l1] = 0.0f;
            }
            for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
                states[i].fVec1[l2] = 0.0f;
            }
            for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
                states[i].fRec1[l3] = 0.0f;
            }
        }
    }

    void update_run_channel() {
        // initialize run_channel based on input types
        void (Sttest::*new_run_channel)(Sttest_state *state);
        if (input->rate == 'b') {
            input = new Upsample(-1, input->chans, input);
        }
        new_run_channel = &Sttest::chan_acc_a;
        run_channel = new_run_channel;
    }

    void print_sources(int indent, bool print_flag) {
        input->print_tree(indent, print_flag, "input");
    }

    void repl_input(Ugen_ptr ugen) {
        input->unref(&input);
        init_input(ugen);
        update_run_channel();
    }

    void set_input(int chan, float f) {
        input->const_set(chan, f, "Sttest::set_input");
    }

    void init_input(Ugen_ptr ugen) { init_param(ugen, input, &input_stride); }

    void chan_acc_a(Sttest_state *state) {
        FAUSTFLOAT* input0 = input_samps;
        FAUSTFLOAT* input1 = input_samps + input_stride;
        FAUSTFLOAT* output0 = out_samps;
        FAUSTFLOAT* output1 = out_samps + BL;
        float fSlow0 = 1.0f / std::tan(fConst0 * float(hz1));
        float fSlow1 = 1.0f / (fSlow0 + 1.0f);
        float fSlow2 = 1.0f - fSlow0;
        float fSlow3 = 1.0f / std::tan(fConst0 * float(hz2));
        float fSlow4 = 1.0f / (fSlow3 + 1.0f);
        float fSlow5 = 1.0f - fSlow3;
        for (int i0 = 0; i0 < BL; i0 = i0 + 1) {
            float fTemp0 = float(input0[i0]);
            state->fVec0[0] = fTemp0;
            state->fRec0[0] = -(fSlow1 * (fSlow2 * state->fRec0[1] - (fTemp0 + state->fVec0[1])));
            output0[i0] = FAUSTFLOAT(state->fRec0[0]);
            float fTemp1 = float(input1[i0]);
            state->fVec1[0] = fTemp1;
            state->fRec1[0] = -(fSlow4 * (fSlow5 * state->fRec1[1] - (fTemp1 + state->fVec1[1])));
            output1[i0] = FAUSTFLOAT(state->fRec1[0]);
            state->fVec0[1] = state->fVec0[0];
            state->fRec0[1] = state->fRec0[0];
            state->fVec1[1] = state->fVec1[0];
            state->fRec1[1] = state->fRec1[0];
        }
    }

    void real_run() {
        input_samps = input->run(current_block);  // update input
        if (((input->flags) & TERMINATED) &&
            (flags & CAN_TERMINATE)) {
            terminate(ACTION_TERM);
        }
        Sttest_state *state = states.get_array();
        (this->*run_channel)(state);
    }
};
#endif
