/* noisegate -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "noisegate.h"

const char *Noisegate_name = "Noisegate";

/* O2SM INTERFACE: /arco/noisegate/new int32 id, int32 chans, int32 input, int32 threshold, int32 attack, int32 hold, int32 release;
 */
void arco_noisegate_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t input = argv[2]->i;
    int32_t threshold = argv[3]->i;
    int32_t attack = argv[4]->i;
    int32_t hold = argv[5]->i;
    int32_t release = argv[6]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(input_ugen, input, "arco_noisegate_new");
    ANY_UGEN_FROM_ID(threshold_ugen, threshold, "arco_noisegate_new");
    ANY_UGEN_FROM_ID(attack_ugen, attack, "arco_noisegate_new");
    ANY_UGEN_FROM_ID(hold_ugen, hold, "arco_noisegate_new");
    ANY_UGEN_FROM_ID(release_ugen, release, "arco_noisegate_new");

    new Noisegate(id, chans, input_ugen, threshold_ugen, attack_ugen, hold_ugen, release_ugen);
}


/* O2SM INTERFACE: /arco/noisegate/repl_input int32 id, int32 input_id;
 */
static void arco_noisegate_repl_input(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t input_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_repl_input");
    ANY_UGEN_FROM_ID(input, input_id, "arco_noisegate_repl_input");
    noisegate->repl_input(input);
}


/* O2SM INTERFACE: /arco/noisegate/set_input int32 id, int32 chan, float val;
 */
static void arco_noisegate_set_input (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_set_input");
    noisegate->set_input(chan, val);
}


/* O2SM INTERFACE: /arco/noisegate/repl_threshold int32 id, int32 threshold_id;
 */
static void arco_noisegate_repl_threshold(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t threshold_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_repl_threshold");
    ANY_UGEN_FROM_ID(threshold, threshold_id, "arco_noisegate_repl_threshold");
    noisegate->repl_threshold(threshold);
}


/* O2SM INTERFACE: /arco/noisegate/set_threshold int32 id, int32 chan, float val;
 */
static void arco_noisegate_set_threshold (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_set_threshold");
    noisegate->set_threshold(chan, val);
}


/* O2SM INTERFACE: /arco/noisegate/repl_attack int32 id, int32 attack_id;
 */
static void arco_noisegate_repl_attack(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t attack_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_repl_attack");
    ANY_UGEN_FROM_ID(attack, attack_id, "arco_noisegate_repl_attack");
    noisegate->repl_attack(attack);
}


/* O2SM INTERFACE: /arco/noisegate/set_attack int32 id, int32 chan, float val;
 */
static void arco_noisegate_set_attack (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_set_attack");
    noisegate->set_attack(chan, val);
}


/* O2SM INTERFACE: /arco/noisegate/repl_hold int32 id, int32 hold_id;
 */
static void arco_noisegate_repl_hold(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t hold_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_repl_hold");
    ANY_UGEN_FROM_ID(hold, hold_id, "arco_noisegate_repl_hold");
    noisegate->repl_hold(hold);
}


/* O2SM INTERFACE: /arco/noisegate/set_hold int32 id, int32 chan, float val;
 */
static void arco_noisegate_set_hold (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_set_hold");
    noisegate->set_hold(chan, val);
}


/* O2SM INTERFACE: /arco/noisegate/repl_release int32 id, int32 release_id;
 */
static void arco_noisegate_repl_release(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t release_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_repl_release");
    ANY_UGEN_FROM_ID(release, release_id, "arco_noisegate_repl_release");
    noisegate->repl_release(release);
}


/* O2SM INTERFACE: /arco/noisegate/set_release int32 id, int32 chan, float val;
 */
static void arco_noisegate_set_release (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Noisegate, noisegate, id, "arco_noisegate_set_release");
    noisegate->set_release(chan, val);
}


static void noisegate_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/noisegate/new", "iiiiiii", arco_noisegate_new,
                    NULL, true, true);
    o2sm_method_new("/arco/noisegate/repl_input", "ii",
                    arco_noisegate_repl_input, NULL, true, true);
    o2sm_method_new("/arco/noisegate/set_input", "iif",
                    arco_noisegate_set_input, NULL, true, true);
    o2sm_method_new("/arco/noisegate/repl_threshold", "ii",
                    arco_noisegate_repl_threshold, NULL, true, true);
    o2sm_method_new("/arco/noisegate/set_threshold", "iif",
                    arco_noisegate_set_threshold, NULL, true, true);
    o2sm_method_new("/arco/noisegate/repl_attack", "ii",
                    arco_noisegate_repl_attack, NULL, true, true);
    o2sm_method_new("/arco/noisegate/set_attack", "iif",
                    arco_noisegate_set_attack, NULL, true, true);
    o2sm_method_new("/arco/noisegate/repl_hold", "ii",
                    arco_noisegate_repl_hold, NULL, true, true);
    o2sm_method_new("/arco/noisegate/set_hold", "iif",
                    arco_noisegate_set_hold, NULL, true, true);
    o2sm_method_new("/arco/noisegate/repl_release", "ii",
                    arco_noisegate_repl_release, NULL, true, true);
    o2sm_method_new("/arco/noisegate/set_release", "iif",
                    arco_noisegate_set_release, NULL, true, true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer noisegate_init_obj(noisegate_init);
