/* sineb -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "sineb.h"

const char *Sineb_name = "Sineb";

/* O2SM INTERFACE: /arco/sineb/new int32 id, int32 chans, int32 freq, int32 amp;
 */
void arco_sineb_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t freq = argv[2]->i;
    int32_t amp = argv[3]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(freq_ugen,freq, "arco_sineb_new");
    ANY_UGEN_FROM_ID(amp_ugen,amp, "arco_sineb_new");

    new Sineb(id, chans, freq_ugen, amp_ugen);
}


/* O2SM INTERFACE: /arco/sineb/repl_freq int32 id, int32 freq_id;
 */
static void arco_sineb_repl_freq(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t freq_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Sineb, sineb, id, "arco_sineb_repl_freq");
    ANY_UGEN_FROM_ID(freq, freq_id, "arco_sineb_repl_freq");
    sineb->repl_freq(freq);
}


/* O2SM INTERFACE: /arco/sineb/set_freq int32 id, int32 chan, float val;
 */
static void arco_sineb_set_freq(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Sineb, sineb, id, "arco_sineb_repl_freq");
    sineb->set_freq(chan, val);
}


/* O2SM INTERFACE: /arco/sineb/repl_amp int32 id, int32 amp_id;
 */
static void arco_sineb_repl_amp(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t amp_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Sineb, sineb, id, "arco_sineb_repl_amp");
    ANY_UGEN_FROM_ID(amp, amp_id, "arco_sineb_repl_amp");
    sineb->repl_amp(amp);
}


/* O2SM INTERFACE: /arco/sineb/set_amp int32 id, int32 chan, float val;
 */
static void arco_sineb_set_amp(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Sineb, sineb, id, "arco_sineb_repl_amp");
    sineb->set_amp(chan, val);
}


static void sineb_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/sineb/new", "iiii", arco_sineb_new, NULL, true,
                     true);
    o2sm_method_new("/arco/sineb/repl_freq", "ii", arco_sineb_repl_freq, NULL,
                     true, true);
    o2sm_method_new("/arco/sineb/set_freq", "iif", arco_sineb_set_freq, NULL,
                     true, true);
    o2sm_method_new("/arco/sineb/repl_amp", "ii", arco_sineb_repl_amp, NULL,
                     true, true);
    o2sm_method_new("/arco/sineb/set_amp", "iif", arco_sineb_set_amp, NULL,
                     true, true);
    // END INTERFACE INITIALIZATION

}

Initializer sineb_init_obj(sineb_init);
