/* sineb -- unit generator for arco
 *
 * generated by f2a.py
 */

/*------------- BEGIN FAUST PREAMBLE -------------*/

/* ------------------------------------------------------------
name: "sineb"
Code generated with Faust 2.75.7 (https://faust.grame.fr)
Compilation options: -lang cpp -os -light -ct 1 -cn Sineb -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */

#ifndef  __Sineb_H__
#define  __Sineb_H__

#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif 

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#ifndef FAUSTCLASS 
#define FAUSTCLASS Sineb
#endif

#ifdef __APPLE__ 
#define exp10f __exp10f
#define exp10 __exp10
#endif

#if defined(_WIN32)
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif

class SinebSIG0 {
    
  private:
    
    int iVec0[2];
    int iRec0[2];
    
  public:
    
    int getNumInputsSinebSIG0() {
        return 0;
    }
    int getNumOutputsSinebSIG0() {
        return 1;
    }
    
    void instanceInitSinebSIG0(int sample_rate) {
        for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
            iVec0[l0] = 0;
        }
        for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
            iRec0[l1] = 0;
        }
    }
    
    void fillSinebSIG0(int count, float* table) {
        for (int i1 = 0; i1 < count; i1 = i1 + 1) {
            iVec0[0] = 1;
            iRec0[0] = (iVec0[1] + iRec0[1]) % 65536;
            table[i1] = std::sin(9.58738e-05f * float(iRec0[0]));
            iVec0[1] = iVec0[0];
            iRec0[1] = iRec0[0];
        }
    }

};

static SinebSIG0* newSinebSIG0() { return (SinebSIG0*)new SinebSIG0(); }
static void deleteSinebSIG0(SinebSIG0* dsp) { delete dsp; }

static float ftbl0SinebSIG0[65536];
/*-------------- END FAUST PREAMBLE --------------*/

extern const char *Sineb_name;

class Sineb : public Ugen {
public:
    struct Sineb_state {
        FAUSTFLOAT fEntry0;
        int iVec1[2];
        FAUSTFLOAT fEntry1;
        float fRec1[2];
    };
    Vec<Sineb_state> states;
    void (Sineb::*run_channel)(Sineb_state *state);

    Ugen_ptr freq;
    int freq_stride;
    Sample_ptr freq_samps;

    Ugen_ptr amp;
    int amp_stride;
    Sample_ptr amp_samps;

    float fConst0;

    Sineb(int id, int nchans, Ugen_ptr freq_, Ugen_ptr amp_) :
            Ugen(id, 'b', nchans) {
        freq = freq_;
        amp = amp_;
        flags = CAN_TERMINATE;
        states.set_size(chans);
        fConst0 = 1.0f / std::min<float>(1.92e+05f, std::max<float>(1.0f, float(BR)));
        init_freq(freq);
        init_amp(amp);
    }

    ~Sineb() {
        freq->unref();
        amp->unref();
    }

    const char *classname() { return Sineb_name; }

    void initialize_channel_states() {
        for (int i = 0; i < chans; i++) {
            for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
                states[i].iVec1[l2] = 0;
            }
            for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
                states[i].fRec1[l3] = 0.0f;
            }
        }
    }

    void print_sources(int indent, bool print_flag) {
        freq->print_tree(indent, print_flag, "freq");
        amp->print_tree(indent, print_flag, "amp");
    }

    void repl_freq(Ugen_ptr ugen) {
        freq->unref();
        init_freq(ugen);
    }

    void repl_amp(Ugen_ptr ugen) {
        amp->unref();
        init_amp(ugen);
    }

    void set_freq(int chan, float f) {
        freq->const_set(chan, f, "Sineb::set_freq");
    }

    void set_amp(int chan, float f) {
        amp->const_set(chan, f, "Sineb::set_amp");
    }

    void init_freq(Ugen_ptr ugen) { init_param(ugen, freq, &freq_stride); }

    void init_amp(Ugen_ptr ugen) { init_param(ugen, amp, &amp_stride); }

    void real_run() {
        freq_samps = freq->run(current_block);  // update input
        amp_samps = amp->run(current_block);  // update input
        Sineb_state *state = &states[0];
        for (int i = 0; i < chans; i++) {
            float fSlow0 = float(amp_samps[0]);
            float fSlow1 = fConst0 * float(freq_samps[0]);
            state->iVec1[0] = 1;
            float fTemp0 = ((1 - state->iVec1[1]) ? 0.0f : fSlow1 + state->fRec1[1]);
            state->fRec1[0] = fTemp0 - std::floor(fTemp0);
            out_samps[0] = FAUSTFLOAT(fSlow0 * ftbl0SinebSIG0[std::max<int>(0, std::min<int>(int(65536.0f * state->fRec1[0]), 65535))]);
            state->iVec1[1] = state->iVec1[0];
            state->fRec1[1] = state->fRec1[0];
    
            state++;
            out_samps++;
            freq_samps += freq_stride;
            amp_samps += amp_stride;
        }
    }
};
#endif
