# sine.py - constructor implementation
#
# (machine generated by u2f.py)

from arco_ugens import *

def sine(freq, amp, chans=None):
    chans = max_chans(chans, freq, amp)
    return Ugen(new_ugen_id(), "sine", chans, A_RATE, "UU", False, False,
         'freq', freq, "abc", 'amp', amp, "abc")

def sineb(freq, amp, chans=None):
    chans = max_chans(chans, freq, amp)
    return Ugen(new_ugen_id(), "sineb", chans, B_RATE, "UU", False, False,
         'freq', freq, "bc", 'amp', amp, "bc")

