# monodistortion.py - constructor implementation
#
# (machine generated by u2f.py)

from arco_ugens import *

def monodistortion(input, gain, tone, volume, chans=None):
    chans = max_chans(chans, input, gain, tone, volume)
    return Ugen(new_ugen_id(), "monodistortion", chans, A_RATE, "UUUU", False,
         False, 'input', input, "a", 'gain', gain, "bc", 'tone', tone, "bc", 'volume',
         volume, "bc")

