/* multb -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "multb.h"

const char *Multb_name = "Multb";

/* O2SM INTERFACE: /arco/multb/new int32 id, int32 chans, int32 x1, int32 x2;
 */
void arco_multb_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t x1 = argv[2]->i;
    int32_t x2 = argv[3]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(x1_ugen,x1, "arco_multb_new");
    ANY_UGEN_FROM_ID(x2_ugen,x2, "arco_multb_new");

    new Multb(id, chans, x1_ugen, x2_ugen);
}


/* O2SM INTERFACE: /arco/multb/repl_x1 int32 id, int32 x1_id;
 */
static void arco_multb_repl_x1(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t x1_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Multb, multb, id, "arco_multb_repl_x1");
    ANY_UGEN_FROM_ID(x1, x1_id, "arco_multb_repl_x1");
    multb->repl_x1(x1);
}


/* O2SM INTERFACE: /arco/multb/set_x1 int32 id, int32 chan, float val;
 */
static void arco_multb_set_x1(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Multb, multb, id, "arco_multb_repl_x1");
    multb->set_x1(chan, val);
}


/* O2SM INTERFACE: /arco/multb/repl_x2 int32 id, int32 x2_id;
 */
static void arco_multb_repl_x2(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t x2_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Multb, multb, id, "arco_multb_repl_x2");
    ANY_UGEN_FROM_ID(x2, x2_id, "arco_multb_repl_x2");
    multb->repl_x2(x2);
}


/* O2SM INTERFACE: /arco/multb/set_x2 int32 id, int32 chan, float val;
 */
static void arco_multb_set_x2(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Multb, multb, id, "arco_multb_repl_x2");
    multb->set_x2(chan, val);
}


static void multb_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/multb/new", "iiii", arco_multb_new, NULL, true,
                    true);
    o2sm_method_new("/arco/multb/repl_x1", "ii", arco_multb_repl_x1, NULL,
                    true, true);
    o2sm_method_new("/arco/multb/set_x1", "iif", arco_multb_set_x1, NULL,
                    true, true);
    o2sm_method_new("/arco/multb/repl_x2", "ii", arco_multb_repl_x2, NULL,
                    true, true);
    o2sm_method_new("/arco/multb/set_x2", "iif", arco_multb_set_x2, NULL,
                    true, true);
    // END INTERFACE INITIALIZATION

}

Initializer multb_init_obj(multb_init);
