/* highpassb -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "highpassb.h"

const char *Highpassb_name = "Highpassb";

/* O2SM INTERFACE: /arco/highpassb/new int32 id, int32 chans, int32 input, int32 cutoff;
 */
void arco_highpassb_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t input = argv[2]->i;
    int32_t cutoff = argv[3]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(input_ugen, input, "arco_highpassb_new");
    ANY_UGEN_FROM_ID(cutoff_ugen, cutoff, "arco_highpassb_new");

    new Highpassb(id, chans, input_ugen, cutoff_ugen);
}


/* O2SM INTERFACE: /arco/highpassb/repl_input int32 id, int32 input_id;
 */
static void arco_highpassb_repl_input(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t input_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Highpassb, highpassb, id, "arco_highpassb_repl_input");
    ANY_UGEN_FROM_ID(input, input_id, "arco_highpassb_repl_input");
    highpassb->repl_input(input);
}


/* O2SM INTERFACE: /arco/highpassb/set_input int32 id, int32 chan, float val;
 */
static void arco_highpassb_set_input (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Highpassb, highpassb, id, "arco_highpassb_set_input");
    highpassb->set_input(chan, val);
}


/* O2SM INTERFACE: /arco/highpassb/repl_cutoff int32 id, int32 cutoff_id;
 */
static void arco_highpassb_repl_cutoff(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t cutoff_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Highpassb, highpassb, id, "arco_highpassb_repl_cutoff");
    ANY_UGEN_FROM_ID(cutoff, cutoff_id, "arco_highpassb_repl_cutoff");
    highpassb->repl_cutoff(cutoff);
}


/* O2SM INTERFACE: /arco/highpassb/set_cutoff int32 id, int32 chan, float val;
 */
static void arco_highpassb_set_cutoff (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Highpassb, highpassb, id, "arco_highpassb_set_cutoff");
    highpassb->set_cutoff(chan, val);
}


static void highpassb_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/highpassb/new", "iiii", arco_highpassb_new, NULL,
                    true, true);
    o2sm_method_new("/arco/highpassb/repl_input", "ii",
                    arco_highpassb_repl_input, NULL, true, true);
    o2sm_method_new("/arco/highpassb/set_input", "iif",
                    arco_highpassb_set_input, NULL, true, true);
    o2sm_method_new("/arco/highpassb/repl_cutoff", "ii",
                    arco_highpassb_repl_cutoff, NULL, true, true);
    o2sm_method_new("/arco/highpassb/set_cutoff", "iif",
                    arco_highpassb_set_cutoff, NULL, true, true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer highpassb_init_obj(highpassb_init);
