/* highpass -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "highpass.h"

const char *Highpass_name = "Highpass";

/* O2SM INTERFACE: /arco/highpass/new int32 id, int32 chans, int32 input, int32 cutoff;
 */
void arco_highpass_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t input = argv[2]->i;
    int32_t cutoff = argv[3]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(input_ugen, input, "arco_highpass_new");
    ANY_UGEN_FROM_ID(cutoff_ugen, cutoff, "arco_highpass_new");

    new Highpass(id, chans, input_ugen, cutoff_ugen);
}


/* O2SM INTERFACE: /arco/highpass/repl_input int32 id, int32 input_id;
 */
static void arco_highpass_repl_input(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t input_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Highpass, highpass, id, "arco_highpass_repl_input");
    ANY_UGEN_FROM_ID(input, input_id, "arco_highpass_repl_input");
    highpass->repl_input(input);
}


/* O2SM INTERFACE: /arco/highpass/set_input int32 id, int32 chan, float val;
 */
static void arco_highpass_set_input (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Highpass, highpass, id, "arco_highpass_set_input");
    highpass->set_input(chan, val);
}


/* O2SM INTERFACE: /arco/highpass/repl_cutoff int32 id, int32 cutoff_id;
 */
static void arco_highpass_repl_cutoff(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t cutoff_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Highpass, highpass, id, "arco_highpass_repl_cutoff");
    ANY_UGEN_FROM_ID(cutoff, cutoff_id, "arco_highpass_repl_cutoff");
    highpass->repl_cutoff(cutoff);
}


/* O2SM INTERFACE: /arco/highpass/set_cutoff int32 id, int32 chan, float val;
 */
static void arco_highpass_set_cutoff (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Highpass, highpass, id, "arco_highpass_set_cutoff");
    highpass->set_cutoff(chan, val);
}


static void highpass_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/highpass/new", "iiii", arco_highpass_new, NULL,
                    true, true);
    o2sm_method_new("/arco/highpass/repl_input", "ii",
                    arco_highpass_repl_input, NULL, true, true);
    o2sm_method_new("/arco/highpass/set_input", "iif",
                    arco_highpass_set_input, NULL, true, true);
    o2sm_method_new("/arco/highpass/repl_cutoff", "ii",
                    arco_highpass_repl_cutoff, NULL, true, true);
    o2sm_method_new("/arco/highpass/set_cutoff", "iif",
                    arco_highpass_set_cutoff, NULL, true, true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer highpass_init_obj(highpass_init);
