/* delayvi -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "delayvi.h"

const char *Delayvi_name = "Delayvi";

/* O2SM INTERFACE: /arco/delayvi/new int32 id, int32 chans, int32 input, int32 delay, float maxdelay;
 */
void arco_delayvi_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t input = argv[2]->i;
    int32_t delay = argv[3]->i;
    float maxdelay = argv[4]->f;
    // end unpack message

    ANY_UGEN_FROM_ID(input_ugen, input, "arco_delayvi_new");
    ANY_UGEN_FROM_ID(delay_ugen, delay, "arco_delayvi_new");

    new Delayvi(id, chans, input_ugen, delay_ugen, maxdelay);
}


/* O2SM INTERFACE: /arco/delayvi/repl_input int32 id, int32 input_id;
 */
static void arco_delayvi_repl_input(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t input_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Delayvi, delayvi, id, "arco_delayvi_repl_input");
    ANY_UGEN_FROM_ID(input, input_id, "arco_delayvi_repl_input");
    delayvi->repl_input(input);
}


/* O2SM INTERFACE: /arco/delayvi/set_input int32 id, int32 chan, float val;
 */
static void arco_delayvi_set_input (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Delayvi, delayvi, id, "arco_delayvi_set_input");
    delayvi->set_input(chan, val);
}


/* O2SM INTERFACE: /arco/delayvi/repl_delay int32 id, int32 delay_id;
 */
static void arco_delayvi_repl_delay(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t delay_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Delayvi, delayvi, id, "arco_delayvi_repl_delay");
    ANY_UGEN_FROM_ID(delay, delay_id, "arco_delayvi_repl_delay");
    delayvi->repl_delay(delay);
}


/* O2SM INTERFACE: /arco/delayvi/set_delay int32 id, int32 chan, float val;
 */
static void arco_delayvi_set_delay (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Delayvi, delayvi, id, "arco_delayvi_set_delay");
    delayvi->set_delay(chan, val);
}


static void delayvi_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/delayvi/new", "iiiif", arco_delayvi_new, NULL,
                    true, true);
    o2sm_method_new("/arco/delayvi/repl_input", "ii",
                    arco_delayvi_repl_input, NULL, true, true);
    o2sm_method_new("/arco/delayvi/set_input", "iif",
                    arco_delayvi_set_input, NULL, true, true);
    o2sm_method_new("/arco/delayvi/repl_delay", "ii",
                    arco_delayvi_repl_delay, NULL, true, true);
    o2sm_method_new("/arco/delayvi/set_delay", "iif",
                    arco_delayvi_set_delay, NULL, true, true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer delayvi_init_obj(delayvi_init);
