/* multx -- unit generator for arco
 *
 * generated by f2a.py, extended by Roger B. Dannennberg
 * Nov 2023
 *
 * multx is a Mult with an initial value, so audo * blockrate
 * does not necessarily start with a ramp from zero.
 *
 * Only the second factor, x2, can be provided with an initial
 * value.
 */

#include "arcougen.h"
#include "multx.h"

const char *Multx_name = "Multx";

/* O2SM INTERFACE: /arco/multx/new int32 id, int32 chans, int32 x1, int32 x2,
                                   float x2_init;
 */
void arco_multx_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t x1 = argv[2]->i;
    int32_t x2 = argv[3]->i;
    float x2_init = argv[4]->f;
    // end unpack message

    ANY_UGEN_FROM_ID(x1_ugen,x1, "arco_multx_new");
    ANY_UGEN_FROM_ID(x2_ugen,x2, "arco_multx_new");

    new Multx(id, chans, x1_ugen, x2_ugen, x2_init);
}


/* O2SM INTERFACE: /arco/multx/repl_x1 int32 id, int32 x1_id;
 */
static void arco_multx_repl_x1(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t x1_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Multx, multx, id, "arco_multx_repl_x1");
    ANY_UGEN_FROM_ID(x1, x1_id, "arco_multx_repl_x1");
    multx->repl_x1(x1);
}


/* O2SM INTERFACE: /arco/multx/set_x1 int32 id, int32 chan, float val;
 */
static void arco_multx_set_x1(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Multx, multx, id, "arco_multx_repl_x1");
    multx->set_x1(chan, val);
}


/* O2SM INTERFACE: /arco/multx/repl_x2 int32 id, int32 x2_id;
 */
static void arco_multx_repl_x2(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t x2_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Multx, multx, id, "arco_multx_repl_x2");
    ANY_UGEN_FROM_ID(x2, x2_id, "arco_multx_repl_x2");
    multx->repl_x2(x2);
}


/* O2SM INTERFACE: /arco/multx/set_x2 int32 id, int32 chan, float val;
 */
static void arco_multx_set_x2(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Multx, multx, id, "arco_multx_repl_x2");
    multx->set_x2(chan, val);
}


static void multx_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/multx/new", "iiiif", arco_multx_new, NULL, true,
                    true);
    o2sm_method_new("/arco/multx/repl_x1", "ii", arco_multx_repl_x1, NULL, true,
                    true);
    o2sm_method_new("/arco/multx/set_x1", "iif", arco_multx_set_x1, NULL, true,
                    true);
    o2sm_method_new("/arco/multx/repl_x2", "ii", arco_multx_repl_x2, NULL, true,
                    true);
    o2sm_method_new("/arco/multx/set_x2", "iif", arco_multx_set_x2, NULL, true,
                    true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer multx_init_obj(multx_init);
