/* zitarev -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "zitarev.h"

const char *Zitarev_name = "Zitarev";

/* O2SM INTERFACE: /arco/zitarev/new int32 id, int32 input, int32 wet, int32 gain, int32 rt60;
 */
void arco_zitarev_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t input = argv[1]->i;
    int32_t wet = argv[2]->i;
    int32_t gain = argv[3]->i;
    int32_t rt60 = argv[4]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(input_ugen, input, "arco_zitarev_new");
    ANY_UGEN_FROM_ID(wet_ugen, wet, "arco_zitarev_new");
    ANY_UGEN_FROM_ID(gain_ugen, gain, "arco_zitarev_new");
    ANY_UGEN_FROM_ID(rt60_ugen, rt60, "arco_zitarev_new");

    new Zitarev(id, input_ugen, wet_ugen, gain_ugen, rt60_ugen);
}


/* O2SM INTERFACE: /arco/zitarev/repl_input int32 id, int32 input_id;
 */
static void arco_zitarev_repl_input(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t input_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Zitarev, zitarev, id, "arco_zitarev_repl_input");
    ANY_UGEN_FROM_ID(input, input_id, "arco_zitarev_repl_input");
    zitarev->repl_input(input);
}


/* O2SM INTERFACE: /arco/zitarev/set_input int32 id, int32 chan, float val;
 */
static void arco_zitarev_set_input (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Zitarev, zitarev, id, "arco_zitarev_set_input");
    zitarev->set_input(chan, val);
}


/* O2SM INTERFACE: /arco/zitarev/repl_wet int32 id, int32 wet_id;
 */
static void arco_zitarev_repl_wet(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t wet_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Zitarev, zitarev, id, "arco_zitarev_repl_wet");
    ANY_UGEN_FROM_ID(wet, wet_id, "arco_zitarev_repl_wet");
    zitarev->repl_wet(wet);
}


/* O2SM INTERFACE: /arco/zitarev/set_wet int32 id, int32 chan, float val;
 */
static void arco_zitarev_set_wet (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Zitarev, zitarev, id, "arco_zitarev_set_wet");
    zitarev->set_wet(chan, val);
}


/* O2SM INTERFACE: /arco/zitarev/repl_gain int32 id, int32 gain_id;
 */
static void arco_zitarev_repl_gain(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t gain_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Zitarev, zitarev, id, "arco_zitarev_repl_gain");
    ANY_UGEN_FROM_ID(gain, gain_id, "arco_zitarev_repl_gain");
    zitarev->repl_gain(gain);
}


/* O2SM INTERFACE: /arco/zitarev/set_gain int32 id, int32 chan, float val;
 */
static void arco_zitarev_set_gain (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Zitarev, zitarev, id, "arco_zitarev_set_gain");
    zitarev->set_gain(chan, val);
}


/* O2SM INTERFACE: /arco/zitarev/repl_rt60 int32 id, int32 rt60_id;
 */
static void arco_zitarev_repl_rt60(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t rt60_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Zitarev, zitarev, id, "arco_zitarev_repl_rt60");
    ANY_UGEN_FROM_ID(rt60, rt60_id, "arco_zitarev_repl_rt60");
    zitarev->repl_rt60(rt60);
}


/* O2SM INTERFACE: /arco/zitarev/set_rt60 int32 id, int32 chan, float val;
 */
static void arco_zitarev_set_rt60 (O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Zitarev, zitarev, id, "arco_zitarev_set_rt60");
    zitarev->set_rt60(chan, val);
}


static void zitarev_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/zitarev/new", "iiiii", arco_zitarev_new, NULL,
                    true, true);
    o2sm_method_new("/arco/zitarev/repl_input", "ii",
                    arco_zitarev_repl_input, NULL, true, true);
    o2sm_method_new("/arco/zitarev/set_input", "iif",
                    arco_zitarev_set_input, NULL, true, true);
    o2sm_method_new("/arco/zitarev/repl_wet", "ii", arco_zitarev_repl_wet,
                    NULL, true, true);
    o2sm_method_new("/arco/zitarev/set_wet", "iif", arco_zitarev_set_wet,
                    NULL, true, true);
    o2sm_method_new("/arco/zitarev/repl_gain", "ii", arco_zitarev_repl_gain,
                    NULL, true, true);
    o2sm_method_new("/arco/zitarev/set_gain", "iif", arco_zitarev_set_gain,
                    NULL, true, true);
    o2sm_method_new("/arco/zitarev/repl_rt60", "ii", arco_zitarev_repl_rt60,
                    NULL, true, true);
    o2sm_method_new("/arco/zitarev/set_rt60", "iif", arco_zitarev_set_rt60,
                    NULL, true, true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer zitarev_init_obj(zitarev_init);
