/* zitarev -- unit generator for arco
 *
 * generated by f2a.py
 */

/*------------- BEGIN FAUST PREAMBLE -------------*/

/* ------------------------------------------------------------
name: "zitarev"
Code generated with Faust 2.75.7 (https://faust.grame.fr)
Compilation options: -lang cpp -light -ct 1 -cn Zitarev -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */

#ifndef  __Zitarev_H__
#define  __Zitarev_H__

#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif 

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#ifndef FAUSTCLASS 
#define FAUSTCLASS Zitarev
#endif

#ifdef __APPLE__ 
#define exp10f __exp10f
#define exp10 __exp10
#endif

#if defined(_WIN32)
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif

static float Zitarev_faustpower2_f(float value) {
    return value * value;
}
/*-------------- END FAUST PREAMBLE --------------*/

extern const char *Zitarev_name;

class Zitarev : public Ugen {
public:
    struct Zitarev_state {
        FAUSTFLOAT fEntry0;
        float fRec0[2];
        FAUSTFLOAT fEntry1;
        float fRec13[2];
        int IOTA0;
        float fVec0[32768];
        float fVec1[16384];
        float fVec2[2048];
        float fRec11[2];
        float fRec16[2];
        float fVec3[32768];
        float fVec4[4096];
        float fRec14[2];
        float fRec19[2];
        float fVec5[16384];
        float fVec6[4096];
        float fRec17[2];
        float fRec22[2];
        float fVec7[32768];
        float fVec8[4096];
        float fRec20[2];
        float fRec25[2];
        float fVec9[16384];
        float fVec10[16384];
        float fVec11[2048];
        float fRec23[2];
        float fRec28[2];
        float fVec12[16384];
        float fVec13[4096];
        float fRec26[2];
        float fRec31[2];
        float fVec14[16384];
        float fVec15[2048];
        float fRec29[2];
        float fRec34[2];
        float fVec16[16384];
        float fVec17[4096];
        float fRec32[2];
        float fRec3[2];
        float fRec4[2];
        float fRec5[2];
        float fRec6[2];
        float fRec7[2];
        float fRec8[2];
        float fRec9[2];
        float fRec10[2];
        float fRec2[3];
        float fRec1[3];
        FAUSTFLOAT fEntry2;
        float fRec35[2];
        float fRec37[3];
        float fRec36[3];
    };
    Vec<Zitarev_state> states;
    void (Zitarev::*run_channel)(Zitarev_state *state);

    Ugen_ptr input;
    int input_stride;
    Sample_ptr input_samps;

    Ugen_ptr wet;
    int wet_stride;
    Sample_ptr wet_samps;

    Ugen_ptr gain;
    int gain_stride;
    Sample_ptr gain_samps;

    Ugen_ptr rt60;
    int rt60_stride;
    Sample_ptr rt60_samps;

    float fConst0;
    float fConst1;
    float fConst2;
    float fConst3;
    float fConst4;
    float fConst5;
    float fConst6;
    float fConst7;
    float fConst8;
    int iConst9;
    int iConst10;
    int iConst11;
    float fConst12;
    float fConst13;
    float fConst14;
    int iConst15;
    int iConst16;
    float fConst17;
    float fConst18;
    float fConst19;
    int iConst20;
    int iConst21;
    float fConst22;
    float fConst23;
    float fConst24;
    int iConst25;
    int iConst26;
    float fConst27;
    float fConst28;
    float fConst29;
    int iConst30;
    int iConst31;
    float fConst32;
    float fConst33;
    float fConst34;
    int iConst35;
    int iConst36;
    float fConst37;
    float fConst38;
    float fConst39;
    int iConst40;
    int iConst41;
    float fConst42;
    float fConst43;
    float fConst44;
    int iConst45;
    int iConst46;
    float fConst47;
    float fConst48;
    float fConst49;
    float fConst50;
    float fConst51;
    float fConst52;

    Zitarev(int id, Ugen_ptr input_, Ugen_ptr wet_, Ugen_ptr gain_, Ugen_ptr rt60_) :
            Ugen(id, 'a', 2) {
        input = input_;
        wet = wet_;
        gain = gain_;
        rt60 = rt60_;
        flags = CAN_TERMINATE;
        states.set_size(chans);
        fConst0 = std::min<float>(1.92e+05f, std::max<float>(1.0f, float(AR)));
        fConst1 = 44.1f / fConst0;
        fConst2 = 1.0f - fConst1;
        fConst3 = 1979.2034f / fConst0;
        fConst4 = (1.0f - fConst3) / (fConst3 + 1.0f);
        fConst5 = std::floor(0.219991f * fConst0 + 0.5f);
        fConst6 = 6.9077554f * (fConst5 / fConst0);
        fConst7 = std::cos(37699.113f / fConst0);
        fConst8 = std::floor(0.019123f * fConst0 + 0.5f);
        iConst9 = int(std::min<float>(16384.0f, std::max<float>(0.0f, fConst5 - fConst8)));
        iConst10 = int(std::min<float>(8192.0f, std::max<float>(0.0f, 0.06f * fConst0)));
        iConst11 = int(std::min<float>(1024.0f, std::max<float>(0.0f, fConst8 + -1.0f)));
        fConst12 = std::floor(0.256891f * fConst0 + 0.5f);
        fConst13 = 6.9077554f * (fConst12 / fConst0);
        fConst14 = std::floor(0.027333f * fConst0 + 0.5f);
        iConst15 = int(std::min<float>(16384.0f, std::max<float>(0.0f, fConst12 - fConst14)));
        iConst16 = int(std::min<float>(2048.0f, std::max<float>(0.0f, fConst14 + -1.0f)));
        fConst17 = std::floor(0.192303f * fConst0 + 0.5f);
        fConst18 = 6.9077554f * (fConst17 / fConst0);
        fConst19 = std::floor(0.029291f * fConst0 + 0.5f);
        iConst20 = int(std::min<float>(8192.0f, std::max<float>(0.0f, fConst17 - fConst19)));
        iConst21 = int(std::min<float>(2048.0f, std::max<float>(0.0f, fConst19 + -1.0f)));
        fConst22 = std::floor(0.210389f * fConst0 + 0.5f);
        fConst23 = 6.9077554f * (fConst22 / fConst0);
        fConst24 = std::floor(0.024421f * fConst0 + 0.5f);
        iConst25 = int(std::min<float>(16384.0f, std::max<float>(0.0f, fConst22 - fConst24)));
        iConst26 = int(std::min<float>(2048.0f, std::max<float>(0.0f, fConst24 + -1.0f)));
        fConst27 = std::floor(0.125f * fConst0 + 0.5f);
        fConst28 = 6.9077554f * (fConst27 / fConst0);
        fConst29 = std::floor(0.013458f * fConst0 + 0.5f);
        iConst30 = int(std::min<float>(8192.0f, std::max<float>(0.0f, fConst27 - fConst29)));
        iConst31 = int(std::min<float>(1024.0f, std::max<float>(0.0f, fConst29 + -1.0f)));
        fConst32 = std::floor(0.174713f * fConst0 + 0.5f);
        fConst33 = 6.9077554f * (fConst32 / fConst0);
        fConst34 = std::floor(0.022904f * fConst0 + 0.5f);
        iConst35 = int(std::min<float>(8192.0f, std::max<float>(0.0f, fConst32 - fConst34)));
        iConst36 = int(std::min<float>(2048.0f, std::max<float>(0.0f, fConst34 + -1.0f)));
        fConst37 = std::floor(0.153129f * fConst0 + 0.5f);
        fConst38 = 6.9077554f * (fConst37 / fConst0);
        fConst39 = std::floor(0.020346f * fConst0 + 0.5f);
        iConst40 = int(std::min<float>(8192.0f, std::max<float>(0.0f, fConst37 - fConst39)));
        iConst41 = int(std::min<float>(1024.0f, std::max<float>(0.0f, fConst39 + -1.0f)));
        fConst42 = std::floor(0.127837f * fConst0 + 0.5f);
        fConst43 = 6.9077554f * (fConst42 / fConst0);
        fConst44 = std::floor(0.031604f * fConst0 + 0.5f);
        iConst45 = int(std::min<float>(8192.0f, std::max<float>(0.0f, fConst42 - fConst44)));
        iConst46 = int(std::min<float>(2048.0f, std::max<float>(0.0f, fConst44 + -1.0f)));
        fConst47 = std::cos(fConst3) * (fConst4 + 1.0f);
        fConst48 = 9424.778f / fConst0;
        fConst49 = (1.0f - fConst48) / (fConst48 + 1.0f);
        fConst50 = std::cos(fConst48) * (fConst49 + 1.0f);
        fConst51 = 2.0f * fConst49;
        fConst52 = 2.0f * fConst50;
        init_input(input);
        init_wet(wet);
        init_gain(gain);
        init_rt60(rt60);
        run_channel = (void (Zitarev::*)(Zitarev_state *)) 0;
        update_run_channel();
    }

    ~Zitarev() {
        input->unref(&input);
        wet->unref(&wet);
        gain->unref(&gain);
        rt60->unref(&rt60);
    }

    const char *classname() { return Zitarev_name; }

#if ARCO_REF_DEBUG
    // for tracing tree of Ugens
    bool get_ref(int i, Ugen **child) {
        if (i == 0) { *child = input;
        } else if (i == 1) { *child = wet;
        } else if (i == 2) { *child = gain;
        } else if (i == 3) { *child = rt60;
        } else { return false;
        }
        return true;
    }
#endif

    void initialize_channel_states() {
        for (int i = 0; i < chans; i++) {
            for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
                states[i].fRec0[l0] = 0.0f;
            }
            for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
                states[i].fRec13[l1] = 0.0f;
            }
            states[i].IOTA0 = 0;
            for (int l2 = 0; l2 < 32768; l2 = l2 + 1) {
                states[i].fVec0[l2] = 0.0f;
            }
            for (int l3 = 0; l3 < 16384; l3 = l3 + 1) {
                states[i].fVec1[l3] = 0.0f;
            }
            for (int l4 = 0; l4 < 2048; l4 = l4 + 1) {
                states[i].fVec2[l4] = 0.0f;
            }
            for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
                states[i].fRec11[l5] = 0.0f;
            }
            for (int l6 = 0; l6 < 2; l6 = l6 + 1) {
                states[i].fRec16[l6] = 0.0f;
            }
            for (int l7 = 0; l7 < 32768; l7 = l7 + 1) {
                states[i].fVec3[l7] = 0.0f;
            }
            for (int l8 = 0; l8 < 4096; l8 = l8 + 1) {
                states[i].fVec4[l8] = 0.0f;
            }
            for (int l9 = 0; l9 < 2; l9 = l9 + 1) {
                states[i].fRec14[l9] = 0.0f;
            }
            for (int l10 = 0; l10 < 2; l10 = l10 + 1) {
                states[i].fRec19[l10] = 0.0f;
            }
            for (int l11 = 0; l11 < 16384; l11 = l11 + 1) {
                states[i].fVec5[l11] = 0.0f;
            }
            for (int l12 = 0; l12 < 4096; l12 = l12 + 1) {
                states[i].fVec6[l12] = 0.0f;
            }
            for (int l13 = 0; l13 < 2; l13 = l13 + 1) {
                states[i].fRec17[l13] = 0.0f;
            }
            for (int l14 = 0; l14 < 2; l14 = l14 + 1) {
                states[i].fRec22[l14] = 0.0f;
            }
            for (int l15 = 0; l15 < 32768; l15 = l15 + 1) {
                states[i].fVec7[l15] = 0.0f;
            }
            for (int l16 = 0; l16 < 4096; l16 = l16 + 1) {
                states[i].fVec8[l16] = 0.0f;
            }
            for (int l17 = 0; l17 < 2; l17 = l17 + 1) {
                states[i].fRec20[l17] = 0.0f;
            }
            for (int l18 = 0; l18 < 2; l18 = l18 + 1) {
                states[i].fRec25[l18] = 0.0f;
            }
            for (int l19 = 0; l19 < 16384; l19 = l19 + 1) {
                states[i].fVec9[l19] = 0.0f;
            }
            for (int l20 = 0; l20 < 16384; l20 = l20 + 1) {
                states[i].fVec10[l20] = 0.0f;
            }
            for (int l21 = 0; l21 < 2048; l21 = l21 + 1) {
                states[i].fVec11[l21] = 0.0f;
            }
            for (int l22 = 0; l22 < 2; l22 = l22 + 1) {
                states[i].fRec23[l22] = 0.0f;
            }
            for (int l23 = 0; l23 < 2; l23 = l23 + 1) {
                states[i].fRec28[l23] = 0.0f;
            }
            for (int l24 = 0; l24 < 16384; l24 = l24 + 1) {
                states[i].fVec12[l24] = 0.0f;
            }
            for (int l25 = 0; l25 < 4096; l25 = l25 + 1) {
                states[i].fVec13[l25] = 0.0f;
            }
            for (int l26 = 0; l26 < 2; l26 = l26 + 1) {
                states[i].fRec26[l26] = 0.0f;
            }
            for (int l27 = 0; l27 < 2; l27 = l27 + 1) {
                states[i].fRec31[l27] = 0.0f;
            }
            for (int l28 = 0; l28 < 16384; l28 = l28 + 1) {
                states[i].fVec14[l28] = 0.0f;
            }
            for (int l29 = 0; l29 < 2048; l29 = l29 + 1) {
                states[i].fVec15[l29] = 0.0f;
            }
            for (int l30 = 0; l30 < 2; l30 = l30 + 1) {
                states[i].fRec29[l30] = 0.0f;
            }
            for (int l31 = 0; l31 < 2; l31 = l31 + 1) {
                states[i].fRec34[l31] = 0.0f;
            }
            for (int l32 = 0; l32 < 16384; l32 = l32 + 1) {
                states[i].fVec16[l32] = 0.0f;
            }
            for (int l33 = 0; l33 < 4096; l33 = l33 + 1) {
                states[i].fVec17[l33] = 0.0f;
            }
            for (int l34 = 0; l34 < 2; l34 = l34 + 1) {
                states[i].fRec32[l34] = 0.0f;
            }
            for (int l35 = 0; l35 < 2; l35 = l35 + 1) {
                states[i].fRec3[l35] = 0.0f;
            }
            for (int l36 = 0; l36 < 2; l36 = l36 + 1) {
                states[i].fRec4[l36] = 0.0f;
            }
            for (int l37 = 0; l37 < 2; l37 = l37 + 1) {
                states[i].fRec5[l37] = 0.0f;
            }
            for (int l38 = 0; l38 < 2; l38 = l38 + 1) {
                states[i].fRec6[l38] = 0.0f;
            }
            for (int l39 = 0; l39 < 2; l39 = l39 + 1) {
                states[i].fRec7[l39] = 0.0f;
            }
            for (int l40 = 0; l40 < 2; l40 = l40 + 1) {
                states[i].fRec8[l40] = 0.0f;
            }
            for (int l41 = 0; l41 < 2; l41 = l41 + 1) {
                states[i].fRec9[l41] = 0.0f;
            }
            for (int l42 = 0; l42 < 2; l42 = l42 + 1) {
                states[i].fRec10[l42] = 0.0f;
            }
            for (int l43 = 0; l43 < 3; l43 = l43 + 1) {
                states[i].fRec2[l43] = 0.0f;
            }
            for (int l44 = 0; l44 < 3; l44 = l44 + 1) {
                states[i].fRec1[l44] = 0.0f;
            }
            for (int l45 = 0; l45 < 2; l45 = l45 + 1) {
                states[i].fRec35[l45] = 0.0f;
            }
            for (int l46 = 0; l46 < 3; l46 = l46 + 1) {
                states[i].fRec37[l46] = 0.0f;
            }
            for (int l47 = 0; l47 < 3; l47 = l47 + 1) {
                states[i].fRec36[l47] = 0.0f;
            }
        }
    }

    void update_run_channel() {
        // initialize run_channel based on input types
        void (Zitarev::*new_run_channel)(Zitarev_state *state);
        if (input->rate == 'b') {
            input = new Upsample(-1, input->chans, input);
        }
        if (wet->rate == 'a') {
            wet = new Dnsampleb(-1, wet->chans, wet, LOWPASS500);
        }
        if (gain->rate == 'a') {
            gain = new Dnsampleb(-1, gain->chans, gain, LOWPASS500);
        }
        if (rt60->rate == 'a') {
            rt60 = new Dnsampleb(-1, rt60->chans, rt60, LOWPASS500);
        }
        new_run_channel = &Zitarev::chan_abbb_a;
        run_channel = new_run_channel;
    }

    void print_sources(int indent, bool print_flag) {
        input->print_tree(indent, print_flag, "input");
        wet->print_tree(indent, print_flag, "wet");
        gain->print_tree(indent, print_flag, "gain");
        rt60->print_tree(indent, print_flag, "rt60");
    }

    void repl_input(Ugen_ptr ugen) {
        input->unref(&input);
        init_input(ugen);
        update_run_channel();
    }

    void repl_wet(Ugen_ptr ugen) {
        wet->unref(&wet);
        init_wet(ugen);
        update_run_channel();
    }

    void repl_gain(Ugen_ptr ugen) {
        gain->unref(&gain);
        init_gain(ugen);
        update_run_channel();
    }

    void repl_rt60(Ugen_ptr ugen) {
        rt60->unref(&rt60);
        init_rt60(ugen);
        update_run_channel();
    }

    void set_input(int chan, float f) {
        input->const_set(chan, f, "Zitarev::set_input");
    }

    void set_wet(int chan, float f) {
        wet->const_set(chan, f, "Zitarev::set_wet");
    }

    void set_gain(int chan, float f) {
        gain->const_set(chan, f, "Zitarev::set_gain");
    }

    void set_rt60(int chan, float f) {
        rt60->const_set(chan, f, "Zitarev::set_rt60");
    }

    void init_input(Ugen_ptr ugen) { init_param(ugen, input, &input_stride); }

    void init_wet(Ugen_ptr ugen) { init_param(ugen, wet, NULL); }

    void init_gain(Ugen_ptr ugen) { init_param(ugen, gain, NULL); }

    void init_rt60(Ugen_ptr ugen) { init_param(ugen, rt60, NULL); }

    void chan_abbb_a(Zitarev_state *state) {
        FAUSTFLOAT* input0 = input_samps;
        FAUSTFLOAT* input1 = input_samps + input_stride;
        FAUSTFLOAT* output0 = out_samps;
        FAUSTFLOAT* output1 = out_samps + BL;
        float fSlow0 = fConst1 * float(gain_samps[0]);
        float fSlow1 = float(rt60_samps[0]);
        float fSlow2 = std::exp(-(fConst6 / fSlow1));
        float fSlow3 = Zitarev_faustpower2_f(fSlow2);
        float fSlow4 = 1.0f - fConst7 * fSlow3;
        float fSlow5 = 1.0f - fSlow3;
        float fSlow6 = std::sqrt(std::max<float>(0.0f, Zitarev_faustpower2_f(fSlow4) / Zitarev_faustpower2_f(fSlow5) + -1.0f));
        float fSlow7 = fSlow4 / fSlow5;
        float fSlow8 = fSlow2 * (fSlow6 + (1.0f - fSlow7));
        float fSlow9 = fSlow7 - fSlow6;
        float fSlow10 = std::exp(-(fConst13 / fSlow1));
        float fSlow11 = Zitarev_faustpower2_f(fSlow10);
        float fSlow12 = 1.0f - fConst7 * fSlow11;
        float fSlow13 = 1.0f - fSlow11;
        float fSlow14 = std::sqrt(std::max<float>(0.0f, Zitarev_faustpower2_f(fSlow12) / Zitarev_faustpower2_f(fSlow13) + -1.0f));
        float fSlow15 = fSlow12 / fSlow13;
        float fSlow16 = fSlow10 * (fSlow14 + (1.0f - fSlow15));
        float fSlow17 = fSlow15 - fSlow14;
        float fSlow18 = std::exp(-(fConst18 / fSlow1));
        float fSlow19 = Zitarev_faustpower2_f(fSlow18);
        float fSlow20 = 1.0f - fConst7 * fSlow19;
        float fSlow21 = 1.0f - fSlow19;
        float fSlow22 = std::sqrt(std::max<float>(0.0f, Zitarev_faustpower2_f(fSlow20) / Zitarev_faustpower2_f(fSlow21) + -1.0f));
        float fSlow23 = fSlow20 / fSlow21;
        float fSlow24 = fSlow18 * (fSlow22 + (1.0f - fSlow23));
        float fSlow25 = fSlow23 - fSlow22;
        float fSlow26 = std::exp(-(fConst23 / fSlow1));
        float fSlow27 = Zitarev_faustpower2_f(fSlow26);
        float fSlow28 = 1.0f - fConst7 * fSlow27;
        float fSlow29 = 1.0f - fSlow27;
        float fSlow30 = std::sqrt(std::max<float>(0.0f, Zitarev_faustpower2_f(fSlow28) / Zitarev_faustpower2_f(fSlow29) + -1.0f));
        float fSlow31 = fSlow28 / fSlow29;
        float fSlow32 = fSlow26 * (fSlow30 + (1.0f - fSlow31));
        float fSlow33 = fSlow31 - fSlow30;
        float fSlow34 = std::exp(-(fConst28 / fSlow1));
        float fSlow35 = Zitarev_faustpower2_f(fSlow34);
        float fSlow36 = 1.0f - fConst7 * fSlow35;
        float fSlow37 = 1.0f - fSlow35;
        float fSlow38 = std::sqrt(std::max<float>(0.0f, Zitarev_faustpower2_f(fSlow36) / Zitarev_faustpower2_f(fSlow37) + -1.0f));
        float fSlow39 = fSlow36 / fSlow37;
        float fSlow40 = fSlow34 * (fSlow38 + (1.0f - fSlow39));
        float fSlow41 = fSlow39 - fSlow38;
        float fSlow42 = std::exp(-(fConst33 / fSlow1));
        float fSlow43 = Zitarev_faustpower2_f(fSlow42);
        float fSlow44 = 1.0f - fConst7 * fSlow43;
        float fSlow45 = 1.0f - fSlow43;
        float fSlow46 = std::sqrt(std::max<float>(0.0f, Zitarev_faustpower2_f(fSlow44) / Zitarev_faustpower2_f(fSlow45) + -1.0f));
        float fSlow47 = fSlow44 / fSlow45;
        float fSlow48 = fSlow42 * (fSlow46 + (1.0f - fSlow47));
        float fSlow49 = fSlow47 - fSlow46;
        float fSlow50 = std::exp(-(fConst38 / fSlow1));
        float fSlow51 = Zitarev_faustpower2_f(fSlow50);
        float fSlow52 = 1.0f - fConst7 * fSlow51;
        float fSlow53 = 1.0f - fSlow51;
        float fSlow54 = std::sqrt(std::max<float>(0.0f, Zitarev_faustpower2_f(fSlow52) / Zitarev_faustpower2_f(fSlow53) + -1.0f));
        float fSlow55 = fSlow52 / fSlow53;
        float fSlow56 = fSlow50 * (fSlow54 + (1.0f - fSlow55));
        float fSlow57 = fSlow55 - fSlow54;
        float fSlow58 = std::exp(-(fConst43 / fSlow1));
        float fSlow59 = Zitarev_faustpower2_f(fSlow58);
        float fSlow60 = 1.0f - fConst7 * fSlow59;
        float fSlow61 = 1.0f - fSlow59;
        float fSlow62 = std::sqrt(std::max<float>(0.0f, Zitarev_faustpower2_f(fSlow60) / Zitarev_faustpower2_f(fSlow61) + -1.0f));
        float fSlow63 = fSlow60 / fSlow61;
        float fSlow64 = fSlow58 * (fSlow62 + (1.0f - fSlow63));
        float fSlow65 = fSlow63 - fSlow62;
        float fSlow66 = fConst1 * float(wet_samps[0]);
        for (int i0 = 0; i0 < BL; i0 = i0 + 1) {
            state->fRec0[0] = fSlow0 + fConst2 * state->fRec0[1];
            state->fRec13[0] = fSlow8 * state->fRec10[1] + fSlow9 * state->fRec13[1];
            state->fVec0[state->IOTA0 & 32767] = 0.35355338f * state->fRec13[0] + 1e-20f;
            float fTemp0 = 0.6f * state->fRec11[1] + state->fVec0[(state->IOTA0 - iConst9) & 32767];
            float fTemp1 = float(input1[i0]);
            state->fVec1[state->IOTA0 & 16383] = fTemp1;
            float fTemp2 = 0.3f * state->fVec1[(state->IOTA0 - iConst10) & 16383];
            state->fVec2[state->IOTA0 & 2047] = fTemp0 - fTemp2;
            state->fRec11[0] = state->fVec2[(state->IOTA0 - iConst11) & 2047];
            float fRec12 = 0.6f * (fTemp2 - fTemp0);
            state->fRec16[0] = fSlow16 * state->fRec6[1] + fSlow17 * state->fRec16[1];
            state->fVec3[state->IOTA0 & 32767] = 0.35355338f * state->fRec16[0] + 1e-20f;
            float fTemp3 = 0.6f * state->fRec14[1] + state->fVec3[(state->IOTA0 - iConst15) & 32767];
            state->fVec4[state->IOTA0 & 4095] = fTemp3 - fTemp2;
            state->fRec14[0] = state->fVec4[(state->IOTA0 - iConst16) & 4095];
            float fRec15 = 0.6f * (fTemp2 - fTemp3);
            state->fRec19[0] = fSlow24 * state->fRec8[1] + fSlow25 * state->fRec19[1];
            state->fVec5[state->IOTA0 & 16383] = 0.35355338f * state->fRec19[0] + 1e-20f;
            float fTemp4 = state->fVec5[(state->IOTA0 - iConst20) & 16383] + fTemp2 + 0.6f * state->fRec17[1];
            state->fVec6[state->IOTA0 & 4095] = fTemp4;
            state->fRec17[0] = state->fVec6[(state->IOTA0 - iConst21) & 4095];
            float fRec18 = -(0.6f * fTemp4);
            state->fRec22[0] = fSlow32 * state->fRec4[1] + fSlow33 * state->fRec22[1];
            state->fVec7[state->IOTA0 & 32767] = 0.35355338f * state->fRec22[0] + 1e-20f;
            float fTemp5 = fTemp2 + 0.6f * state->fRec20[1] + state->fVec7[(state->IOTA0 - iConst25) & 32767];
            state->fVec8[state->IOTA0 & 4095] = fTemp5;
            state->fRec20[0] = state->fVec8[(state->IOTA0 - iConst26) & 4095];
            float fRec21 = -(0.6f * fTemp5);
            state->fRec25[0] = fSlow40 * state->fRec9[1] + fSlow41 * state->fRec25[1];
            state->fVec9[state->IOTA0 & 16383] = 0.35355338f * state->fRec25[0] + 1e-20f;
            float fTemp6 = float(input0[i0]);
            state->fVec10[state->IOTA0 & 16383] = fTemp6;
            float fTemp7 = 0.3f * state->fVec10[(state->IOTA0 - iConst10) & 16383];
            float fTemp8 = state->fVec9[(state->IOTA0 - iConst30) & 16383] - (fTemp7 + 0.6f * state->fRec23[1]);
            state->fVec11[state->IOTA0 & 2047] = fTemp8;
            state->fRec23[0] = state->fVec11[(state->IOTA0 - iConst31) & 2047];
            float fRec24 = 0.6f * fTemp8;
            state->fRec28[0] = fSlow48 * state->fRec7[1] + fSlow49 * state->fRec28[1];
            state->fVec12[state->IOTA0 & 16383] = 0.35355338f * state->fRec28[0] + 1e-20f;
            float fTemp9 = fTemp7 + state->fVec12[(state->IOTA0 - iConst35) & 16383] - 0.6f * state->fRec26[1];
            state->fVec13[state->IOTA0 & 4095] = fTemp9;
            state->fRec26[0] = state->fVec13[(state->IOTA0 - iConst36) & 4095];
            float fRec27 = 0.6f * fTemp9;
            state->fRec31[0] = fSlow56 * state->fRec3[1] + fSlow57 * state->fRec31[1];
            state->fVec14[state->IOTA0 & 16383] = 0.35355338f * state->fRec31[0] + 1e-20f;
            float fTemp10 = state->fVec14[(state->IOTA0 - iConst40) & 16383] + fTemp7 - 0.6f * state->fRec29[1];
            state->fVec15[state->IOTA0 & 2047] = fTemp10;
            state->fRec29[0] = state->fVec15[(state->IOTA0 - iConst41) & 2047];
            float fRec30 = 0.6f * fTemp10;
            state->fRec34[0] = fSlow64 * state->fRec5[1] + fSlow65 * state->fRec34[1];
            state->fVec16[state->IOTA0 & 16383] = 0.35355338f * state->fRec34[0] + 1e-20f;
            float fTemp11 = state->fVec16[(state->IOTA0 - iConst45) & 16383] - (fTemp7 + 0.6f * state->fRec32[1]);
            state->fVec17[state->IOTA0 & 4095] = fTemp11;
            state->fRec32[0] = state->fVec17[(state->IOTA0 - iConst46) & 4095];
            float fRec33 = 0.6f * fTemp11;
            float fTemp12 = fRec27 + fRec33;
            float fTemp13 = fRec24 + fTemp12;
            state->fRec3[0] = state->fRec11[1] + state->fRec14[1] + state->fRec17[1] + state->fRec20[1] + state->fRec23[1] + state->fRec26[1] + state->fRec29[1] + fRec12 + fRec15 + fRec18 + fRec21 + fTemp13 + fRec30 + state->fRec32[1];
            state->fRec4[0] = state->fRec23[1] + state->fRec26[1] + state->fRec29[1] + fTemp13 + fRec30 + state->fRec32[1] - (state->fRec11[1] + state->fRec14[1] + state->fRec17[1] + state->fRec20[1] + fRec12 + fRec15 + fRec21 + fRec18);
            float fTemp14 = fRec33 + fRec24;
            state->fRec5[0] = state->fRec17[1] + state->fRec20[1] + state->fRec26[1] + state->fRec29[1] + fRec18 + fRec27 + fRec21 + fRec30 - (state->fRec11[1] + state->fRec14[1] + state->fRec23[1] + fRec12 + fRec15 + fTemp14 + state->fRec32[1]);
            state->fRec6[0] = state->fRec11[1] + state->fRec14[1] + state->fRec26[1] + state->fRec29[1] + fRec12 + fRec27 + fRec15 + fRec30 - (state->fRec17[1] + state->fRec20[1] + state->fRec23[1] + fRec18 + fRec21 + fTemp14 + state->fRec32[1]);
            float fTemp15 = fRec27 + fRec24;
            state->fRec7[0] = state->fRec14[1] + state->fRec20[1] + state->fRec29[1] + fRec15 + fRec33 + fRec21 + fRec30 + state->fRec32[1] - (state->fRec11[1] + state->fRec17[1] + state->fRec23[1] + state->fRec26[1] + fRec12 + fRec18 + fTemp15);
            state->fRec8[0] = state->fRec11[1] + state->fRec17[1] + state->fRec29[1] + fRec12 + fRec33 + fRec18 + fRec30 + state->fRec32[1] - (state->fRec14[1] + state->fRec20[1] + state->fRec23[1] + state->fRec26[1] + fRec15 + fRec21 + fTemp15);
            state->fRec9[0] = state->fRec11[1] + state->fRec20[1] + state->fRec23[1] + state->fRec29[1] + fRec12 + fRec24 + fRec21 + fRec30 - (state->fRec14[1] + state->fRec17[1] + state->fRec26[1] + fRec15 + fRec18 + fTemp12 + state->fRec32[1]);
            state->fRec10[0] = state->fRec14[1] + state->fRec17[1] + state->fRec23[1] + state->fRec29[1] + fRec15 + fRec24 + fRec18 + fRec30 - (state->fRec11[1] + state->fRec20[1] + state->fRec26[1] + fRec12 + fRec21 + fTemp12 + state->fRec32[1]);
            float fTemp16 = 0.37f * (state->fRec4[0] + state->fRec5[0]);
            float fTemp17 = fConst47 * state->fRec2[1];
            float fTemp18 = fTemp16 + fTemp17;
            state->fRec2[0] = fTemp18 - fConst4 * state->fRec2[2];
            float fTemp19 = fConst4 * state->fRec2[0];
            state->fRec1[0] = 0.5f * (fTemp19 + fTemp16 + state->fRec2[2] - fTemp17 + (state->fRec2[2] + fTemp19 - fTemp18)) + fConst50 * state->fRec1[1] - fConst49 * state->fRec1[2];
            state->fRec35[0] = fSlow66 + fConst2 * state->fRec35[1];
            float fTemp20 = 1.0f - state->fRec35[0];
            output0[i0] = FAUSTFLOAT(state->fRec0[0] * (0.5f * (2.0f * state->fRec1[2] + fConst51 * state->fRec1[0] - fConst52 * state->fRec1[1]) * state->fRec35[0] + fTemp6 * fTemp20));
            float fTemp21 = 0.37f * (state->fRec4[0] - state->fRec5[0]);
            float fTemp22 = fConst47 * state->fRec37[1];
            float fTemp23 = fTemp21 + fTemp22;
            state->fRec37[0] = fTemp23 - fConst4 * state->fRec37[2];
            float fTemp24 = fConst4 * state->fRec37[0];
            state->fRec36[0] = 0.5f * (fTemp24 + fTemp21 + state->fRec37[2] - fTemp22 + (state->fRec37[2] + fTemp24 - fTemp23)) + fConst50 * state->fRec36[1] - fConst49 * state->fRec36[2];
            output1[i0] = FAUSTFLOAT(state->fRec0[0] * (fTemp1 * fTemp20 + 0.5f * (2.0f * state->fRec36[2] + fConst51 * state->fRec36[0] - fConst52 * state->fRec36[1]) * state->fRec35[0]));
            state->fRec0[1] = state->fRec0[0];
            state->fRec13[1] = state->fRec13[0];
            state->IOTA0 = state->IOTA0 + 1;
            state->fRec11[1] = state->fRec11[0];
            state->fRec16[1] = state->fRec16[0];
            state->fRec14[1] = state->fRec14[0];
            state->fRec19[1] = state->fRec19[0];
            state->fRec17[1] = state->fRec17[0];
            state->fRec22[1] = state->fRec22[0];
            state->fRec20[1] = state->fRec20[0];
            state->fRec25[1] = state->fRec25[0];
            state->fRec23[1] = state->fRec23[0];
            state->fRec28[1] = state->fRec28[0];
            state->fRec26[1] = state->fRec26[0];
            state->fRec31[1] = state->fRec31[0];
            state->fRec29[1] = state->fRec29[0];
            state->fRec34[1] = state->fRec34[0];
            state->fRec32[1] = state->fRec32[0];
            state->fRec3[1] = state->fRec3[0];
            state->fRec4[1] = state->fRec4[0];
            state->fRec5[1] = state->fRec5[0];
            state->fRec6[1] = state->fRec6[0];
            state->fRec7[1] = state->fRec7[0];
            state->fRec8[1] = state->fRec8[0];
            state->fRec9[1] = state->fRec9[0];
            state->fRec10[1] = state->fRec10[0];
            state->fRec2[2] = state->fRec2[1];
            state->fRec2[1] = state->fRec2[0];
            state->fRec1[2] = state->fRec1[1];
            state->fRec1[1] = state->fRec1[0];
            state->fRec35[1] = state->fRec35[0];
            state->fRec37[2] = state->fRec37[1];
            state->fRec37[1] = state->fRec37[0];
            state->fRec36[2] = state->fRec36[1];
            state->fRec36[1] = state->fRec36[0];
        }
    }

    void real_run() {
        input_samps = input->run(current_block);  // update input
        wet_samps = wet->run(current_block);  // update input
        gain_samps = gain->run(current_block);  // update input
        rt60_samps = rt60->run(current_block);  // update input
        Zitarev_state *state = states.get_array();
        (this->*run_channel)(state);
    }
};
#endif
