/* resonb -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "resonb.h"

const char *Resonb_name = "Resonb";

/* O2SM INTERFACE: /arco/resonb/new int32 id, int32 chans, int32 snd, int32 center, int32 q;
 */
void arco_resonb_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t snd = argv[2]->i;
    int32_t center = argv[3]->i;
    int32_t q = argv[4]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(snd_ugen, snd, "arco_resonb_new");
    ANY_UGEN_FROM_ID(center_ugen, center, "arco_resonb_new");
    ANY_UGEN_FROM_ID(q_ugen, q, "arco_resonb_new");

    new Resonb(id, chans, snd_ugen, center_ugen, q_ugen);
}


/* O2SM INTERFACE: /arco/resonb/repl_snd int32 id, int32 snd_id;
 */
static void arco_resonb_repl_snd(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t snd_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Resonb, resonb, id, "arco_resonb_repl_snd");
    ANY_UGEN_FROM_ID(snd, snd_id, "arco_resonb_repl_snd");
    resonb->repl_snd(snd);
}


/* O2SM INTERFACE: /arco/resonb/set_snd int32 id, int32 chan, float val;
 */
static void arco_resonb_set_snd(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Resonb, resonb, id, "arco_resonb_set_snd");
    resonb->set_snd(chan, val);
}


/* O2SM INTERFACE: /arco/resonb/repl_center int32 id, int32 center_id;
 */
static void arco_resonb_repl_center(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t center_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Resonb, resonb, id, "arco_resonb_repl_center");
    ANY_UGEN_FROM_ID(center, center_id, "arco_resonb_repl_center");
    resonb->repl_center(center);
}


/* O2SM INTERFACE: /arco/resonb/set_center int32 id, int32 chan, float val;
 */
static void arco_resonb_set_center(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Resonb, resonb, id, "arco_resonb_set_center");
    resonb->set_center(chan, val);
}


/* O2SM INTERFACE: /arco/resonb/repl_q int32 id, int32 q_id;
 */
static void arco_resonb_repl_q(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t q_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Resonb, resonb, id, "arco_resonb_repl_q");
    ANY_UGEN_FROM_ID(q, q_id, "arco_resonb_repl_q");
    resonb->repl_q(q);
}


/* O2SM INTERFACE: /arco/resonb/set_q int32 id, int32 chan, float val;
 */
static void arco_resonb_set_q(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Resonb, resonb, id, "arco_resonb_set_q");
    resonb->set_q(chan, val);
}


static void resonb_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/resonb/new", "iiiii", arco_resonb_new, NULL,
                    true, true);
    o2sm_method_new("/arco/resonb/repl_snd", "ii", arco_resonb_repl_snd,
                    NULL, true, true);
    o2sm_method_new("/arco/resonb/set_snd", "iif", arco_resonb_set_snd,
                    NULL, true, true);
    o2sm_method_new("/arco/resonb/repl_center", "ii",
                    arco_resonb_repl_center, NULL, true, true);
    o2sm_method_new("/arco/resonb/set_center", "iif",
                    arco_resonb_set_center, NULL, true, true);
    o2sm_method_new("/arco/resonb/repl_q", "ii", arco_resonb_repl_q, NULL,
                    true, true);
    o2sm_method_new("/arco/resonb/set_q", "iif", arco_resonb_set_q, NULL,
                    true, true);
    // END INTERFACE INITIALIZATION

    // "static" initialization code from faust:

}

Initializer resonb_init_obj(resonb_init);
