# reson.py - constructor implementation
#
# (machine generated by u2f.py)

from arco_ugens import *

def reson(input, center, q, chans=None):
    chans = max_chans(chans, input, center, q)
    return Ugen(new_ugen_id(), "reson", chans, A_RATE, "UUU", False, False,
         'input', input, "a", 'center', center, "abc", 'q', q, "abc")

def resonb(input, center, q, chans=None):
    chans = max_chans(chans, input, center, q)
    return Ugen(new_ugen_id(), "resonb", chans, B_RATE, "UUU", False, False,
         'input', input, "bc", 'center', center, "bc", 'q', q, "bc")

