# lowpass.py - constructor implementation
#
# (machine generated by u2f.py)

from arco_ugens import *

def lowpass(input, cutoff, chans=None):
    chans = max_chans(chans, input, cutoff)
    return Ugen(new_ugen_id(), "lowpass", chans, A_RATE, "UU", False, False,
         'input', input, "a", 'cutoff', cutoff, "abc")

def lowpassb(input, cutoff, chans=None):
    chans = max_chans(chans, input, cutoff)
    return Ugen(new_ugen_id(), "lowpassb", chans, B_RATE, "UU", False, False,
         'input', input, "bc", 'cutoff', cutoff, "bc")

