/* lowpass -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "lowpass.h"

const char *Lowpass_name = "Lowpass";

/* O2SM INTERFACE: /arco/lowpass/new int32 id, int32 chans, int32 snd, int32 cutoff;
 */
void arco_lowpass_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chans = argv[1]->i;
    int32_t snd = argv[2]->i;
    int32_t cutoff = argv[3]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(snd_ugen,snd, "arco_lowpass_new");
    ANY_UGEN_FROM_ID(cutoff_ugen,cutoff, "arco_lowpass_new");

    new Lowpass(id, chans, snd_ugen, cutoff_ugen);
}


/* O2SM INTERFACE: /arco/lowpass/repl_snd int32 id, int32 snd_id;
 */
static void arco_lowpass_repl_snd(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t snd_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Lowpass, lowpass, id, "arco_lowpass_repl_snd");
    ANY_UGEN_FROM_ID(snd, snd_id, "arco_lowpass_repl_snd");
    lowpass->repl_snd(snd);
}


/* O2SM INTERFACE: /arco/lowpass/set_snd int32 id, int32 chan, float val;
 */
static void arco_lowpass_set_snd(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Lowpass, lowpass, id, "arco_lowpass_repl_snd");
    lowpass->set_snd(chan, val);
}


/* O2SM INTERFACE: /arco/lowpass/repl_cutoff int32 id, int32 cutoff_id;
 */
static void arco_lowpass_repl_cutoff(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t cutoff_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Lowpass, lowpass, id, "arco_lowpass_repl_cutoff");
    ANY_UGEN_FROM_ID(cutoff, cutoff_id, "arco_lowpass_repl_cutoff");
    lowpass->repl_cutoff(cutoff);
}


/* O2SM INTERFACE: /arco/lowpass/set_cutoff int32 id, int32 chan, float val;
 */
static void arco_lowpass_set_cutoff(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32_t id = argv[0]->i;
    int32_t chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Lowpass, lowpass, id, "arco_lowpass_repl_cutoff");
    lowpass->set_cutoff(chan, val);
}


static void lowpass_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/lowpass/new", "iiii", arco_lowpass_new, NULL, true,
                    true);
    o2sm_method_new("/arco/lowpass/repl_snd", "ii", arco_lowpass_repl_snd,
                    NULL, true, true);
    o2sm_method_new("/arco/lowpass/set_snd", "iif", arco_lowpass_set_snd,
                    NULL, true, true);
    o2sm_method_new("/arco/lowpass/repl_cutoff", "ii",
                    arco_lowpass_repl_cutoff, NULL, true, true);
    o2sm_method_new("/arco/lowpass/set_cutoff", "iif",
                    arco_lowpass_set_cutoff, NULL, true, true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer lowpass_init_obj(lowpass_init);
