/* mult -- unit generator for arco
 *
 * generated by f2a.py
 */

#include "arcougen.h"
#include "mult.h"

const char *Mult_name = "Mult";

/* O2SM INTERFACE: /arco/mult/new int32 id, int32 chans, int32 x1, int32 x2;
 */
void arco_mult_new(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32 id = argv[0]->i;
    int32 chans = argv[1]->i;
    int32 x1 = argv[2]->i;
    int32 x2 = argv[3]->i;
    // end unpack message

    ANY_UGEN_FROM_ID(x1_ugen,x1, "arco_mult_new");
    ANY_UGEN_FROM_ID(x2_ugen,x2, "arco_mult_new");

    new Mult(id, chans, x1_ugen, x2_ugen);
}


/* O2SM INTERFACE: /arco/mult/repl_x1 int32 id, int32 x1_id;
 */
static void arco_mult_repl_x1(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32 id = argv[0]->i;
    int32 x1_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Mult, mult, id, "arco_mult_repl_x1");
    ANY_UGEN_FROM_ID(x1, x1_id, "arco_mult_repl_x1");
    mult->repl_x1(x1);
}


/* O2SM INTERFACE: /arco/mult/set_x1 int32 id, int32 chan, float val;
 */
static void arco_mult_set_x1(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32 id = argv[0]->i;
    int32 chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Mult, mult, id, "arco_mult_repl_x1");
    mult->set_x1(chan, val);
}


/* O2SM INTERFACE: /arco/mult/repl_x2 int32 id, int32 x2_id;
 */
static void arco_mult_repl_x2(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32 id = argv[0]->i;
    int32 x2_id = argv[1]->i;
    // end unpack message

    UGEN_FROM_ID(Mult, mult, id, "arco_mult_repl_x2");
    ANY_UGEN_FROM_ID(x2, x2_id, "arco_mult_repl_x2");
    mult->repl_x2(x2);
}


/* O2SM INTERFACE: /arco/mult/set_x2 int32 id, int32 chan, float val;
 */
static void arco_mult_set_x2(O2SM_HANDLER_ARGS)
{
    // begin unpack message (machine-generated):
    int32 id = argv[0]->i;
    int32 chan = argv[1]->i;
    float val = argv[2]->f;
    // end unpack message

    UGEN_FROM_ID(Mult, mult, id, "arco_mult_repl_x2");
    mult->set_x2(chan, val);
}


static void mult_init()
{
    // O2SM INTERFACE INITIALIZATION: (machine generated)
    o2sm_method_new("/arco/mult/new", "iiii", arco_mult_new, NULL, true, true);
    o2sm_method_new("/arco/mult/repl_x1", "ii", arco_mult_repl_x1, NULL, true, true);
    o2sm_method_new("/arco/mult/set_x1", "iif", arco_mult_set_x1, NULL, true, true);
    o2sm_method_new("/arco/mult/repl_x2", "ii", arco_mult_repl_x2, NULL, true, true);
    o2sm_method_new("/arco/mult/set_x2", "iif", arco_mult_set_x2, NULL, true, true);
    // END INTERFACE INITIALIZATION

    // class initialization code from faust:
}

Initializer mult_init_obj(mult_init);
